name: CI

on:
  push:

jobs:
  ci:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - run: go vet ./...

      - run: go test ./...
